### PR TITLE
compiled tailwindcss locally instread of using cdn

### PR DESCRIPTION
**Pull request by crypt0inf0**
Fix the 404 error (https://cdn.tailwindcss.com/) by some internet provider. I just copy the https://cdn.tailwindcss.com/ content into [tailwindcss.js](https://github.com/crypt0inf0/openalgo/blob/main/static/js/tailwindcss.js) file.

### CODE REVIEW

**Comment by marketcalls** [comment]
Iam considering 

Flask-Assets is a Flask extension that helps manage, bundle, and serve static assets like JavaScript, CSS, and images in a Flask application. It integrates with the webassets library and provides a way to define asset bundles, apply filters (like minification), and cache-bust static files.

Using Flask-Assets is especially important in scenarios where performance and maintainability of assets are a priority. It allows you to:
	1.	Bundle Assets: Combine multiple CSS or JavaScript files into a single file to reduce HTTP requests.
	2.	Minify Files: Reduce the size of CSS and JavaScript files for faster load times.
	3.	Cache Busting: Automatically generate new file versions when assets are updated to avoid browser cache issues.
	4.	Custom Filters: Apply transformations like SCSS, Less, or PostCSS.

Why is it important for a Tailwind-based project?

Tailwind CSS generates a large stylesheet during development, including unused styles. To optimize for production:
	•	You can use Flask-Assets to ensure that the compiled CSS from Tailwind is minified.
	•	Flask-Assets integrates with tools like purgecss or postcss to remove unused Tailwind styles, making the CSS much smaller.

Simple Example with Flask-Assets and Tailwind CSS

Install Requirements

pip install flask-assets
npm install tailwindcss postcss autoprefixer

Project Structure

my_flask_app/
├── static/
│   ├── css/
│   │   ├── input.css
│   │   └── output.css
│   └── dist/
├── templates/
│   └── index.html
├── app.py
├── tailwind.config.js
└── postcss.config.js

Tailwind Configuration (tailwind.config.js)

module.exports = {
  content: ["./templates/**/*.html"],
  theme: {
    extend: {},
  },
  plugins: [],
};

PostCSS Configuration (postcss.config.js)

module.exports = {
  plugins: {
    tailwindcss: {},
    autoprefixer: {},
  },
};

Flask Application (app.py)

from flask import Flask, render_template
from flask_assets import Environment, Bundle

app = Flask(__name__)
assets = Environment(app)

# Define a CSS bundle
css = Bundle(
    "css/output.css",  # Tailwind CSS compiled file
    filters="cssmin",  # Minify CSS
    output="dist/styles.min.css"
)

assets.register("main_css", css)

@app.route("/")
def index():
    return render_template("index.html")

if __name__ == "__main__":
    app.run(debug=True)

Input CSS (static/css/input.css)

@tailwind base;
@tailwind components;
@tailwind utilities;

Build Tailwind CSS

Run these commands:

npx tailwindcss -i ./static/css/input.css -o ./static/css/output.css --watch

HTML Template (templates/index.html)

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Flask Assets with Tailwind</title>
    {{ assets['main_css'] }}
</head>
<body class="bg-gray-100 text-gray-800">
    <div class="container mx-auto mt-10">
        <h1 class="text-3xl font-bold">Hello, Flask-Assets with Tailwind!</h1>
        <p class="mt-4">This is a simple example using Flask-Assets.</p>
    </div>
</body>
</html>

Benefits in this Setup
	1.	Optimized CSS: The Tailwind CSS is compiled, purged, and minified for production use.
	2.	Ease of Updates: Any changes in Tailwind’s input file automatically reflect after recompilation.
	3.	Efficient Caching: Flask-Assets ensures cache busting with unique filenames when assets change.
	4.	Maintainable Workflow: You can add more asset pipelines (e.g., JavaScript bundling) without much effort.

This setup combines Flask-Assets with modern tooling like Tailwind and PostCSS, making the app optimized and ready for production.

**Comment by crypt0inf0** [comment]
## Install Tailwind CSS
Install Tailwind CSS and its peer dev dependencies using npm or yarn:
```
npm install -D tailwindcss postcss postcss-cli autoprefixer
```

## Initialize Tailwind CSS
Create a `tailwind.config.js` file using the following command:
```
npx tailwindcss init
```
This generates a basic configuration file where you can customize your Tailwind setup.

## Create Your CSS File
Create a CSS file (e.g., static/css/styles.css) and include the Tailwind directives:
```
@tailwind base;
@tailwind components;
@tailwind utilities;
```
## Set Up a Build Script
You can compile your Tailwind CSS using the CLI or PostCSS.

Create a `postcss.config.js` file:
```
module.exports = {
  plugins: {
    tailwindcss: {},
    autoprefixer: {},
  },
};
```
Then add the following build script to your `package.json`:
```
"scripts": {
  "build:css": "postcss static/css/styles.css -o static/css/output.css"
}
```

## Configure Your HTML/JS Files
Update the content array in `tailwind.config.js` to include the paths to your HTML, JS, or other files where Tailwind classes are used:
```
module.exports = {
  content: ["./templates/**/*.{html,js}"],
  theme: {
    extend: {},
  },
  plugins: [],
};
```
## Run the Build Process
Use the script you defined to build the CSS:
```
npm run build:css
```

**Comment by crypt0inf0** [comment]
Hot reload using watch command & update `output.css` file instantly for changes in template files.
## CLI Method
Add a script in your `package.json` for building the CSS:
```
"scripts": {
  "build:css": "npx tailwindcss -i ./static/css/styles.css -o ./static/css/output.css --watch"
}
```
## Run the Build Process
Use the script you defined to build the CSS:
```
npm run build:css
```

**Comment by crypt0inf0** [comment]
Closing this commit as it is fixed on 073e937eec383b12da3d66c536bf5e7a95df3b89

**Pull request closed without merging**
